
import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useToast } from "@/components/ui/use-toast";
import { db, auth } from "@/components/auth/firebase-config";
import { doc, setDoc, getDoc, updateDoc } from "firebase/firestore";
import { CV } from "@/types/profile";

export function useResumeForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [jobDescription, setJobDescription] = useState("");
  const [cvNameDialogOpen, setCvNameDialogOpen] = useState(false);
  const [cvName, setCvName] = useState("");
  const [isEditing, setIsEditing] = useState(false);
  
  useEffect(() => {
    // Check if we're editing an existing CV
    const loadCvData = async () => {
      const user = auth.currentUser;
      if (!user) {
        toast({
          title: "Erreur d'authentification",
          description: "Vous devez être connecté pour accéder à vos CVs",
          variant: "destructive",
        });
        navigate("/login");
        return;
      }
      
      if (id && id !== "new") {
        setIsEditing(true);
        
        try {
          const userDocRef = doc(db, "users", user.uid);
          const userDoc = await getDoc(userDocRef);
          
          if (userDoc.exists()) {
            const userData = userDoc.data();
            const cvs = userData.cvs || [];
            const cv = cvs.find((cv: CV) => cv.cv_name === id);
            
            if (cv) {
              setJobDescription(cv.job_raw || "");
              setCvName(cv.cv_name || "");
            } else {
              toast({
                title: "CV introuvable",
                description: "Le CV demandé n'existe pas",
                variant: "destructive",
              });
              navigate("/resumes");
            }
          }
        } catch (error) {
          console.error("Error loading CV data:", error);
          toast({
            title: "Erreur",
            description: "Impossible de charger les données du CV",
            variant: "destructive",
          });
        }
      } else if (id === "new") {
        // For new CV, show the name dialog
        setCvNameDialogOpen(true);
      }
    };
    
    loadCvData();
  }, [id, navigate, toast]);

  const handleGenerateResume = async () => {
    if (!jobDescription.trim()) {
      toast({
        title: "Erreur",
        description: "Veuillez copier la fiche de poste avant de générer un CV",
        variant: "destructive",
      });
      return;
    }

    if (!cvName.trim()) {
      setCvNameDialogOpen(true);
      return;
    }

    const user = auth.currentUser;
    if (!user) {
      toast({
        title: "Erreur d'authentification",
        description: "Vous devez être connecté pour générer un CV",
        variant: "destructive",
      });
      navigate("/login");
      return;
    }

    try {
      toast({
        title: "Génération du CV",
        description: "Votre CV est en cours de génération...",
      });
      
      // Get user document reference
      const userDocRef = doc(db, "users", user.uid);
      const userDoc = await getDoc(userDocRef);
      
      // Get user profile for CV generation if exists
      let profile = null;
      if (userDoc.exists()) {
        const userData = userDoc.data();
        profile = userData.profile;
      }
      
      // Create a new CV object
      const newCV: CV = {
        job_raw: jobDescription,
        cv_name: cvName,
        cv_data: {
          // This would normally be generated by an AI based on the job description and profile
          educations: [],
          lang_of_cv: "français",
          hobbies: profile?.hobbies || "",
          languages: [],
          phone: profile?.head?.phone || "",
          mail: profile?.head?.mail || "",
          title: profile?.head?.title || "",
          sections_name: {
            experience_section_name: "Expérience professionnelle",
            Hobbies_section: "Centres d'intérêt",
            languages_section_name: "Langues",
            skills_section_name: "Compétences",
            education_section_name: "Formation"
          },
          skills: [],
          experiences: [],
          name: profile?.head?.name || ""
        }
      };
      
      // Update the user document
      if (userDoc.exists()) {
        // Get existing CVs or initialize empty array
        const userData = userDoc.data();
        let cvs = userData.cvs || [];
        
        if (isEditing) {
          // Replace the existing CV
          cvs = cvs.map((cv: CV) => cv.cv_name === cvName ? newCV : cv);
        } else {
          // Add the new CV
          cvs.push(newCV);
        }
        
        // Update the document
        await updateDoc(userDocRef, { cvs });
      } else {
        // Create new user document with the CV
        await setDoc(userDocRef, {
          cvs: [newCV],
          profile: profile || {}
        });
      }
      
      toast({
        title: "Succès !",
        description: "Votre CV a été généré avec succès.",
      });
      
      navigate("/resumes");
    } catch (error) {
      console.error("Error generating CV:", error);
      toast({
        title: "Erreur",
        description: "Une erreur est survenue lors de la génération du CV",
        variant: "destructive",
      });
    }
  };
  
  const handleCreateNewCV = async () => {
    if (!cvName.trim()) {
      toast({
        title: "Erreur",
        description: "Veuillez saisir un nom pour votre CV",
        variant: "destructive",
      });
      return;
    }
    
    setCvNameDialogOpen(false);
    
    // If jobDescription is already filled, generate the CV immediately
    if (jobDescription.trim()) {
      await handleGenerateResume();
    }
  };

  return {
    jobDescription,
    setJobDescription,
    cvNameDialogOpen,
    setCvNameDialogOpen,
    cvName,
    setCvName,
    isEditing,
    handleGenerateResume,
    handleCreateNewCV,
    navigate
  };
}
